# credentials:
#   name: "John Doe"
#   email: "jhondow3@gmail.com"
#   full_name: "John Doe"
#   phone: "464454443"
#   # current_location: "Hyderabad"
#   linkedin_url: "https://www.linkedin.com/in/p-sunil-9a9924239"
#   comments: "I am excited to apply for this position!"
# current_location: "Hyderabad"
# resume_path: "resumes/resumee.pdf"
# resume_file: "resumes/resume.pdf"
# full_name: "John Doe"
# first_name: "John"
# last_name: "Doe"
# pronouns : "he/him"
# gender : "Male"
# address: "123 Main St"
# city: "New York"
# state: "New York"
# zip: "10001"
# country: "United States"
# referred : "No"
# compensation : "$100,000 - $120,000"
# work_status : "H1 Visa"
# work_authorization : "I am authorized to work in the country in which this job will be performed"




full_name: "Jhon"
first_name: "Sunil"
last_name: "Poli"
email: "psunil55433@gmail.com"
phone: "+91XXXXXXXXXX"  # Replace with your actual phone number
current_location: "India"
current_company: "WBL"  # Leave empty if not applicable
linkedin: "https://www.linkedin.com/in/sunil-poli"
github: "https://github.com/your-github-username"  # Replace with your actual GitHub profile
portfolio: "https://your-portfolio-url.com"  # Replace with your portfolio URL
experience:
years: 0  # Change if you have experience
domain: "Software Development"
education:
degree: "B.E/B.Tech in Computer Science and Engineering"
university: "PERI Institute of Technology"
graduation_year: 2023
compensation : "$100,000 - $120,000"
work_status : "H1 Visa"
work_authorization : "I am authorized to work in the country in which this job will be performed"
skills:
    - "Java"
    - "Python"
    - "C#"
    - "MySQL"
    - ".NET"
    - "Spring Boot"
    - "React.js"
    - "Docker"
    - "FastAPI"
certifications:
    - "Java Full Stack - JSpiders"
    - "Cyber Security Course"
  
resume_path: "path/to/your/resume.pdf"  # Update with the actual path