full_name: "Malathi kaliappan"
first_name: "malathi"
last_name: "kaliappan"
email: "malathi.kaliappan11@gmail.com "
phone: "925-699-5473"
resume_path: "resumes/Malathi.pdf"  
linkedin: "https://www.linkedin.com/in/malathi-kaliappan/"
current_location: "San Francisco, CA, USA"
current_company: "Pryon"
school: "MIT"
degree: "Bachelor's"
work_auth: "Authorized to work for any employer"



