full_name: "Maryam F Syeda"
ffirst_name: "maryam"
last_name: "syeda"
email: "maryamsyeda.work@gmail.com"
phone: "(209) 831-2991"
resume_path: "resumes/Maryam.pdf" 
linkedin: "https://www.linkedin.com/in/maryam-syeda-52ab956/"
current_location: "Mountain House, CA, USA"
current_company: "Wells Fargo"
school: "MIT"
degree: "Bachelor's"
work_auth: "Authorized to work for any employer"