full_name: "Narasimulu Alli"
first_name: "Narsimlu"
last_name: "Alli "
email: "narasi.mymail@gmail.com"
phone: "469-514-1494"
resume_path: "resumes/Narsimlu.pdf"  # Relative path
linkedin: "https://www.linkedin.com/in/narasimulu-alli/"
current_location: "Dalls,TX, USA"
current_company: "N/A"
school: "MIT"
degree: "Bachelor's"
work_auth: "Authorized to work for any employer"



