first_name: "sindhuri"
last_name: "Siddireddy "
full_name: "Sindhuri Siddireddy"
email: "sindhuri.siddireddy@gmail.com"
phone: "203-824-1798"
resume_path: "resumes/Sindhuri.pdf"  # Relative path
linkedin: "https://www.linkedin.com/in/sindhurisiddireddy/"
location: "pleasanton, CA, USA"
school: "MIT"
degree: "Bachelor's"
current_location: "Pleasanton,CA"
current_company: "Kaiser permanente"
work_auth: "Authorized to work for any employer"




