full_name: "Srutej Kodiganti"
first_name: "srutej"
last_name: "Kodiganti"
email: "srutej.kodiganti@gmail.com"
phone: "(770) 282-9950"
resume_path: "resumes/Srutej.pdf" 
linkedin: "https://www.linkedin.com/in/srutejkodiganti/"
current_location: "Cumming,  GA, USA"
current_company: "Talent Screen"
school: "MIT"
degree: "Bachelor's"
work_auth: "Authorized to work for any employer"