full_name: "John Doe"
first_name: "John"
last_name: "Doe"
email: "johndoe@example.com"
phone: "+1234567890"
resume_path: "path/to/resume.pdf"
linkedin: "https://www.linkedin.com/in/johndoe"
current_location: "New York, NY"
current_company: "Tech Solutions Inc."
school: "University of Technology"
degree: "Bachelor of Science in Computer Science"
work_auth: "Authorized to work in the US"
